apiVersion: v1
kind: Namespace
metadata:
  name: job-hunter
  labels:
    app.kubernetes.io/managed-by: kubectl
    app.kubernetes.io/name: job-hunter
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: job-hunter-quota
  namespace: job-hunter
spec:
  hard:
    requests.memory: "4Gi"
    limits.memory: "10Gi"
    requests.cpu: "2000m"
    limits.cpu: "12000m"
    pods: "60"
