#!/usr/bin/env bash
# Apply pending Alembic database migrations
# Usage: bash infra/scripts/run_migration.sh [--create "migration message"]
#
#   --create "msg"   Generate a new autogenerated migration with the given message

set -euo pipefail

SCRIPTS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
INFRA_DIR="$(cd "$SCRIPTS_DIR/.." && pwd)"
COMPOSE_FILE="$INFRA_DIR/docker-compose.yml"
ENV_FILE="$INFRA_DIR/.env"
COMPOSE="docker compose -f $COMPOSE_FILE --env-file $ENV_FILE"

log() { echo "[$(date '+%Y-%m-%d %H:%M:%S')] $*"; }

if [[ "${1:-}" == "--create" ]]; then
    MSG="${2:?Usage: run_migration.sh --create \"migration message\"}"
    log "Creating new migration: $MSG"
    $COMPOSE exec api alembic -c backend/alembic.ini revision --autogenerate -m "$MSG"
    log "Migration file created. Review it before applying."
else
    log "Applying pending migrations..."
    $COMPOSE exec api alembic -c backend/alembic.ini upgrade head
    log "Migrations applied successfully."
fi
