#!/usr/bin/env bash
# restore.sh — Selectively restore application data from backup.sql into the live k8s DB.
#
# Restored (application data only):
#   candidates            UPDATE existing rows with richer backup data
#   blacklisted_companies UPSERT (ON CONFLICT DO NOTHING)
#   cron_runs             UPSERT (ON CONFLICT DO NOTHING)
#   jobs                  INSERT (table is empty in live DB)
#   embeddings            INSERT
#   send_logs             INSERT
#   direct_send_logs      INSERT
#   search_tasks          INSERT
#
# NOT touched:
#   alembic_version, tenants, users, memberships,
#   billing_subscriptions, notifications, usage_logs
#
# Usage: bash infra/backups/restore.sh
set -euo pipefail

BACKUP="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/backup.sql"
NS="job-hunter"
PG_POD="postgres-0"
PG_USER="jobhunter"
PG_DB="jobhunter"
REMOTE_SQL="/tmp/jh_restore.sql"

log()  { echo ""; echo "▶ $(date '+%H:%M:%S') $*"; }
ok()   { echo "  ✓ $*"; }
fail() { echo "✗ ERROR: $*" >&2; exit 1; }

[[ -f "$BACKUP" ]] || fail "backup.sql not found at $BACKUP"

# ── Build the restore SQL locally ─────────────────────────────────────────────
log "Building restore SQL from backup..."
TMP_SQL=$(mktemp /tmp/jh_restore_XXXXXX.sql)
trap 'rm -f "$TMP_SQL"' EXIT

extract() { sed -n "${1},${2}p" "$BACKUP"; }

cat >> "$TMP_SQL" <<'HEADER'
-- Job Hunter selective restore
-- Generated by infra/backups/restore.sh
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
BEGIN;
HEADER

# ── candidates: UPDATE via temp table ────────────────────────────────────────
cat >> "$TMP_SQL" <<'SQL'

-- Step 1: candidates (UPDATE existing rows)
CREATE TEMP TABLE _candidates_tmp (
  id varchar(36), name varchar, email varchar, skills jsonb,
  years_experience int, resume_url text, target_roles jsonb,
  target_locations jsonb, bio text, linkedin_url text, github_url text,
  is_active boolean, created_at timestamp, updated_at timestamp,
  tenant_id varchar(36), cover_letter_template text, static_cover_letter text
) ON COMMIT DROP;
SQL
echo "COPY _candidates_tmp (id, name, email, skills, years_experience, resume_url, target_roles, target_locations, bio, linkedin_url, github_url, is_active, created_at, updated_at, tenant_id, cover_letter_template, static_cover_letter) FROM stdin;" >> "$TMP_SQL"
extract 420 421 >> "$TMP_SQL"
printf '\\.\n' >> "$TMP_SQL"
cat >> "$TMP_SQL" <<'SQL'
UPDATE candidates c SET
  name = t.name, email = t.email, resume_url = t.resume_url,
  updated_at = t.updated_at, cover_letter_template = t.cover_letter_template,
  static_cover_letter = t.static_cover_letter
FROM _candidates_tmp t WHERE c.id = t.id;
SQL

# ── blacklisted_companies: UPSERT ─────────────────────────────────────────────
cat >> "$TMP_SQL" <<'SQL'

-- Step 2: blacklisted_companies (upsert)
CREATE TEMP TABLE _bc_tmp (
  id varchar(36), tenant_id varchar(36), name varchar, reason text, created_at timestamp
) ON COMMIT DROP;
SQL
echo "COPY _bc_tmp (id, tenant_id, name, reason, created_at) FROM stdin;" >> "$TMP_SQL"
extract 387 411 >> "$TMP_SQL"
printf '\\.\n' >> "$TMP_SQL"
echo "INSERT INTO blacklisted_companies SELECT * FROM _bc_tmp ON CONFLICT DO NOTHING;" >> "$TMP_SQL"

# ── cron_runs: UPSERT ─────────────────────────────────────────────────────────
cat >> "$TMP_SQL" <<'SQL'

-- Step 3: cron_runs (upsert)
CREATE TEMP TABLE _cr_tmp (LIKE cron_runs) ON COMMIT DROP;
SQL
echo "COPY _cr_tmp (id, task_name, started_at, ended_at, duration_ms, status, error_summary, error_traceback, pre_state, post_state, steps, triggered_by, worker_host, celery_task_id) FROM stdin;" >> "$TMP_SQL"
extract 430 1563 >> "$TMP_SQL"
printf '\\.\n' >> "$TMP_SQL"
echo "INSERT INTO cron_runs SELECT * FROM _cr_tmp ON CONFLICT DO NOTHING;" >> "$TMP_SQL"

# ── jobs: INSERT ─────────────────────────────────────────────────────────────
cat >> "$TMP_SQL" <<'SQL'

-- Step 4: jobs (direct insert — table is empty)
SQL
echo "COPY jobs (id, candidate_id, job_title, company, location, job_description, job_url, posted_date, scraped_at, hr_email, company_website, recruiter_name, source_portal, status, dedupe_hash, salary_min, salary_max, salary_currency, job_type, experience_required, raw_data, relevance_score, cover_letter, cover_letter_generated_at, score_breakdown, tenant_id, hr_email_discovery_status, hr_email_discovery_attempts, hr_email_discovered_at, updated_at) FROM stdin;" >> "$TMP_SQL"
extract 3125 5747 >> "$TMP_SQL"
printf '\\.\n' >> "$TMP_SQL"

# ── embeddings: INSERT ────────────────────────────────────────────────────────
cat >> "$TMP_SQL" <<'SQL'

-- Step 5: embeddings
SQL
echo "COPY embeddings (id, job_id, vector_id, embedding_source, embedding_model, embedding_json, created_at, tenant_id, embedding_vector) FROM stdin;" >> "$TMP_SQL"
extract 1620 3116 >> "$TMP_SQL"
printf '\\.\n' >> "$TMP_SQL"

# ── send_logs: INSERT ─────────────────────────────────────────────────────────
cat >> "$TMP_SQL" <<'SQL'

-- Step 6: send_logs
SQL
echo "COPY send_logs (id, job_id, candidate_id, to_email, subject, body_snippet, status, provider, provider_message_id, sent_at, delivered_at, opened_at, clicked_at, error_message, response_webhook_payload, retry_count, tenant_id) FROM stdin;" >> "$TMP_SQL"
extract 5814 7607 >> "$TMP_SQL"
printf '\\.\n' >> "$TMP_SQL"

# ── missing tenants needed by direct_send_logs ───────────────────────────────
cat >> "$TMP_SQL" <<'SQL'

-- Step 7a: ensure "suraj" tenant exists (referenced by direct_send_logs FK)
INSERT INTO tenants (id, name, slug, plan, status, requires_approval, auto_send, score_threshold, created_at)
VALUES ('2f359380-43cf-4f5f-9b71-821cdcca1847', 'suraj', 'suraj', 'free', 'active', false, true, 60, '2026-04-06 16:17:23.440271')
ON CONFLICT DO NOTHING;
SQL

# ── direct_send_logs: INSERT ──────────────────────────────────────────────────
cat >> "$TMP_SQL" <<'SQL'

-- Step 7b: direct_send_logs
SQL
echo "COPY direct_send_logs (id, tenant_id, candidate_id, hr_email, sent_at) FROM stdin;" >> "$TMP_SQL"
extract 1572 1611 >> "$TMP_SQL"
printf '\\.\n' >> "$TMP_SQL"

# ── search_tasks: INSERT ──────────────────────────────────────────────────────
cat >> "$TMP_SQL" <<'SQL'

-- Step 8: search_tasks
SQL
echo "COPY search_tasks (id, candidate_id, job_titles, locations, portals, max_results_per_portal, celery_task_id, status, jobs_found, started_at, completed_at, error, created_at, tasks_total, tasks_completed, tenant_id, jobs_old_skipped, jobs_date_unavailable) FROM stdin;" >> "$TMP_SQL"
extract 5774 5805 >> "$TMP_SQL"
printf '\\.\n' >> "$TMP_SQL"

echo "COMMIT;" >> "$TMP_SQL"

ok "SQL file built ($(wc -l < "$TMP_SQL") lines, $(du -sh "$TMP_SQL" | cut -f1))"

# ── Copy SQL file into the postgres pod ───────────────────────────────────────
log "Copying SQL to pod $PG_POD..."
kubectl cp "$TMP_SQL" "$NS/$PG_POD:$REMOTE_SQL"
ok "Copied to $REMOTE_SQL"

# ── Run the restore ───────────────────────────────────────────────────────────
log "Running restore (jobs+embeddings may take 1-2 min)..."
kubectl exec -n "$NS" "$PG_POD" -- \
  psql -U "$PG_USER" -d "$PG_DB" -v ON_ERROR_STOP=1 -f "$REMOTE_SQL"

# ── Cleanup ───────────────────────────────────────────────────────────────────
kubectl exec -n "$NS" "$PG_POD" -- rm -f "$REMOTE_SQL" 2>/dev/null || true

# ── Verify ────────────────────────────────────────────────────────────────────
log "Verification"
kubectl exec -n "$NS" "$PG_POD" -- psql -U "$PG_USER" -d "$PG_DB" -c "
SELECT table_name AS \"table\", row_count AS \"rows\" FROM (
  SELECT 'jobs'                   AS table_name, count(*)::int AS row_count FROM jobs
  UNION ALL SELECT 'embeddings',               count(*)::int FROM embeddings
  UNION ALL SELECT 'send_logs',                count(*)::int FROM send_logs
  UNION ALL SELECT 'direct_send_logs',         count(*)::int FROM direct_send_logs
  UNION ALL SELECT 'search_tasks',             count(*)::int FROM search_tasks
  UNION ALL SELECT 'cron_runs',                count(*)::int FROM cron_runs
  UNION ALL SELECT 'blacklisted_companies',    count(*)::int FROM blacklisted_companies
  UNION ALL SELECT 'candidates',               count(*)::int FROM candidates
) t ORDER BY table_name;"

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  Restore complete!"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
